# Generated by Django 5.2.1 on 2025-05-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('char_class', models.CharField(max_length=255)),
                ('weapon', models.CharField(blank=True, max_length=255, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('vitality', models.IntegerField(blank=True, null=True)),
                ('agility', models.IntegerField(blank=True, null=True)),
                ('charisma', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('energy', models.IntegerField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='fichas.player')),
            ],
        ),
    ]
