# Generated by Django 5.2.1 on 2025-06-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='photo',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='campaign',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sistema',
            field=models.CharField(default='D&D', max_length=100),
            preserve_default=False,
        ),
    ]
