# Generated by Django 5.2.1 on 2025-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_rename_photo_campaign_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
